titles:
  pT_lep1:
    mpl: "$p_{\\mathrm{T}}(\\ell_1)$"
    rex: "#it{p}_{T}(lep1)"
    unit: "GeV"
  pT_lep2:
    mpl: "$p_{\\mathrm{T}}(\\ell_2)$"
    rex: "#it{p}_{T}(lep2)"
    unit: "GeV"
  pT_jet1:
    mpl: "$p_{\\mathrm{T}}(j_1)$"
    rex: "#it{p}_{T}(jet1)"
    unit: "GeV"
  pT_jet2:
    mpl: "$p_{\\mathrm{T}}(j_2)$"
    rex: "#it{p}_{T}(jet2)"
    unit: "GeV"
  pT_jetS1:
    mpl: "$p_{\\mathrm{T}}{j_{S1}}$"
    rex: "#it{p}_{T}(jetS1)"
    unit: "GeV"
  eta_lep1:
    mpl: "$\\eta(\\ell_1)$"
    rex: "#eta(lep1)"
    unit: "GeV"
  eta_lep2:
    mpl: "$\\eta(\\ell_2)$"
    rex: "#eta(lep2)"
    unit: "GeV"
  eta_jet1:
    mpl: "$\\eta(j_1)$"
    rex: "#eta(jet1)"
    unit: "GeV"
  eta_jet2:
    mpl: "$\\eta(j_2)$"
    rex: "#eta(jet2)"
    unit: "GeV"
  met:
    mpl: "$E_{\\mathrm{T}}^{\\mathrm{miss}}$"
    rex: "#it{E}_{T}^{miss}"
    unit: "GeV"
  psuedoContTagBin_jet1:
    mpl: "$b$-tag bin ($j_1$)"
    rex: "b-tag bin (jet1)"
    unit: ""
  psuedoContTagBin_jet2:
    mpl: "$b$-tag bin ($j_2$)"
    rex: "b-tag bin (jet2)"
    unit: ""
  HT_lep1lep2jet1met:
    mpl: "$H_{T}(\\ell_1\\ell_2j_1E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: "GeV"
  HT_lep1lep2jet1jet2met:
    mpl: "$H_{T}(\\ell_1\\ell_2j_1j_2E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: "GeV"
  HT_jet1jet2:
    mpl: "$H_{T}(j_1j_2)$"
    rex: ""
    unit: ""
  HTratio_lep1lep2_lep1lep2jet1met:
    mpl: ""
    rex: ""
    unit: ""
  HTratio_lep1lep2_lep1lep2jet1jet2met:
    mpl: ""
    rex: ""
    unit: ""
  cent_lep1lep2:
    mpl: "Centrality($\\ell_1\\ell_2$)"
    rex: ""
    unit: ""
  cent_lep1met:
    mpl: ""
    rex: ""
    unit: ""
  cent_lep1lep2jet1:
    mpl: ""
    rex: ""
    unit: ""
  deltaR_jet1_jet2:
    mpl: ""
    rex: ""
    unit: ""
  deltaR_lep1_jet1:
    mpl: ""
    rex: ""
    unit: ""
  deltaR_lep1_jet2:
    mpl: ""
    rex: ""
    unit: ""
  deltaR_lep1_lep2:
    mpl: ""
    rex: ""
    unit: ""
  deltaR_lep1lep2_jet1jet2:
    mpl: ""
    rex: ""
    unit: ""
  deltaR_lep1lep2_jet1jet2met:
    mpl: ""
    rex: ""
    unit: ""
  deltaR_lep2_jet1:
    mpl: ""
    rex: ""
    unit: ""
  deltapT_jet2_met:
    mpl: ""
    rex: ""
    unit: ""
  deltapT_lep1_jet1:
    mpl: ""
    rex: ""
    unit: ""
  deltapT_lep1_lep2:
    mpl: ""
    rex: ""
    unit: ""
  deltapT_lep1lep2_jet1met:
    mpl: ""
    rex: ""
    unit: ""
  deltapT_lep1lep2jet1_met:
    mpl: ""
    rex: ""
    unit: ""
  eom_lep1lep2:
    mpl: ""
    rex: ""
    unit: ""
  mT_jet1met:
    mpl: ""
    rex: ""
    unit: ""
  mT_jet2met:
    mpl: ""
    rex: ""
    unit: ""
  mT_lep2met:
    mpl: ""
    rex: ""
    unit: ""
  mass_lep1jet1:
    mpl: ""
    rex: ""
    unit: ""
  mass_lep1jet1jet2:
    mpl: ""
    rex: ""
    unit: ""
  mass_lep1jet2:
    mpl: ""
    rex: ""
    unit: ""
  mass_lep1lep2jet1jet2:
    mpl: ""
    rex: ""
    unit: ""
  mass_lep2jet1:
    mpl: ""
    rex: ""
    unit: ""
  mass_lep2jet1jet2:
    mpl: ""
    rex: ""
    unit: ""
  mass_lep2jet1met:
    mpl: ""
    rex: ""
    unit: ""
  mass_lep2jet2:
    mpl: ""
    rex: ""
    unit: ""
  pTsys_jet1jet2:
    mpl: ""
    rex: ""
    unit: ""
  pTsys_jet1met:
    mpl: ""
    rex: ""
    unit: ""
  pTsys_lep1lep2:
    mpl: ""
    rex: ""
    unit: ""
  pTsys_lep1lep2jet1:
    mpl: ""
    rex: ""
    unit: ""
  pTsys_lep1lep2jet1jet2met:
    mpl: ""
    rex: ""
    unit: ""
  pTsys_lep1lep2jet1met:
    mpl: ""
    rex: ""
    unit: ""
  pTsys_lep1lep2met:
    mpl: ""
    rex: ""
    unit: ""
  pTHTratio_lep1lep2jet1met:
    mpl: ""
    rex: ""
    unit: ""
  pTHTratio_lep1lep2jet1jet2met:
    mpl: ""
    rex: ""
    unit: ""
  phi_lep1:
    mpl: ""
    rex: ""
    unit: ""
  phi_lep2:
    mpl: ""
    rex: ""
    unit: ""
  phi_jet1:
    mpl: ""
    rex: ""
    unit: ""
  phi_jet2:
    mpl: ""
    rex: ""
    unit: ""
  phi_jetS1:
    mpl: ""
    rex: ""
    unit: ""
  phi_jetF:
    mpl: ""
    rex: ""
    unit: ""
  E_lep1:
    mpl: ""
    rex: ""
    unit: ""
  E_lep2:
    mpl: ""
    rex: ""
    unit: ""
  E_jet1:
    mpl: ""
    rex: ""
    unit: ""
  E_jet2:
    mpl: ""
    rex: ""
    unit: ""
  phi_met:
    mpl: ""
    rex: ""
    unit: ""
  sumet:
    mpl: ""
    rex: ""
    unit: ""
  nsoftjets:
    mpl: "$N$ soft jets"
    rex: "#it{N} soft jets"
    unit: ""
  nsoftbjets:
    mpl: "$N$ soft $b$-jets"
    rex: "#it{N} soft #it{b}-jets"
    unit: ""
  minimaxmbl:
    mpl: ""
    rex: ""
    unit: ""


regions:
  r1j1b:
    - { var: pT_lep1, nbins: 40, xmin: 27.0, xmax: 227.0, log: false }
    - { var: pT_lep2, nbins: 40, xmin: 20.0, xmax: 160.0, log: false }
    - { var: pT_jet1, nbins: 40, xmin: 25.0, xmax: 225.0, log: false }
    - { var: met, nbins: 40, xmin: 0, xmax: 200, log: false }
    - { var: nsoftjets, nbins: 4, xmin: -0.5, xmax: 3.5, log: true }
    - { var: nsoftbjets, nbins: 3, xmin: -0.5, xmax: 2.5, log: true }
    - { var: HT_lep1lep2jet1met, nbins: 40, xmin: 120, xmax: 520, log: false }
  r2j1b:
    - { var: pT_lep1, nbins: 40, xmin: 27.0, xmax: 227.0, log: false }
    - { var: pT_lep2, nbins: 40, xmin: 20.0, xmax: 160.0, log: false }
    - { var: pT_jet1, nbins: 40, xmin: 25.0, xmax: 225.0, log: false }
    - { var: pT_jet2, nbins: 40, xmin: 25.0, xmax: 175.0, log: false }
    - { var: met, nbins: 40, xmin: 0, xmax: 200, log: false }
    - { var: nsoftjets, nbins: 4, xmin: -0.5, xmax: 3.5, log: true }
    - { var: nsoftbjets, nbins: 3, xmin: -0.5, xmax: 2.5, log: true }
    - { var: HT_lep1lep2jet1met, nbins: 40, xmin: 120, xmax: 520, log: false }
    - { var: HT_lep1lep2jet1jet2met, nbins: 40, xmin: 120, xmax: 520, log: false }
  r2j2b:
    - { var: pT_lep1, nbins: 40, xmin: 27.0, xmax: 227.0, log: false }
    - { var: pT_lep2, nbins: 40, xmin: 20.0, xmax: 160.0, log: false }
    - { var: pT_jet1, nbins: 40, xmin: 25.0, xmax: 225.0, log: false }
    - { var: pT_jet2, nbins: 40, xmin: 25.0, xmax: 175.0, log: false }
    - { var: met, nbins: 40, xmin: 0, xmax: 200, log: false }
    - { var: HT_lep1lep2jet1met, nbins: 40, xmin: 120, xmax: 520, log: false }
    - { var: HT_lep1lep2jet1jet2met, nbins: 40, xmin: 120, xmax: 520, log: false }
