titles:
  pT_lep1:
    mpl: "$p_{\\mathrm{T}}(\\ell_1)$"
    rex: "#it{p}_{T}(lep1)"
    unit: "GeV"
  pT_lep2:
    mpl: "$p_{\\mathrm{T}}(\\ell_2)$"
    rex: "#it{p}_{T}(lep2)"
    unit: "GeV"
  pT_jet1:
    mpl: "$p_{\\mathrm{T}}(j_1)$"
    rex: "#it{p}_{T}(jet1)"
    unit: "GeV"
  pT_jet2:
    mpl: "$p_{\\mathrm{T}}(j_2)$"
    rex: "#it{p}_{T}(jet2)"
    unit: "GeV"
  pT_jetS1:
    mpl: "$p_{\\mathrm{T}}(j_{S1})$"
    rex: "#it{p}_{T}(jetS1)"
    unit: "GeV"
  eta_lep1:
    mpl: "$\\eta(\\ell_1)$"
    rex: "#eta(lep1)"
    unit: ""
  eta_lep2:
    mpl: "$\\eta(\\ell_2)$"
    rex: "#eta(lep2)"
    unit: ""
  eta_jet1:
    mpl: "$\\eta(j_1)$"
    rex: "#eta(jet1)"
    unit: ""
  eta_jet2:
    mpl: "$\\eta(j_2)$"
    rex: "#eta(jet2)"
    unit: ""
  met:
    mpl: "$E_{\\mathrm{T}}^{\\mathrm{miss}}$"
    rex: "#it{E}_{T}^{miss}"
    unit: "GeV"
  psuedoContTagBin_jet1:
    mpl: "$b$-tag bin ($j_1$)"
    rex: "b-tag bin (jet1)"
    unit: ""
  psuedoContTagBin_jet2:
    mpl: "$b$-tag bin ($j_2$)"
    rex: "b-tag bin (jet2)"
    unit: ""
  HT_lep1lep2jet1met:
    mpl: "$H_\\mathrm{T}(\\ell_1\\ell_2j_1E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: "#it{H}_{T}(lep1, lep2, jet1, #it{E}_{T}^{miss})"
    unit: "GeV"
  HT_lep1lep2jet1jet2met:
    mpl: "$H_{\\mathrm{T}}(\\ell_1\\ell_2j_1j_2E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: "#it{H}_{T}(lep1, lep2, jet1, jet2, #it{E}_{T}^{miss})"
    unit: "GeV"
  HT_jet1jet2:
    mpl: "$H_{\\mathrm{T}}(j_1j_2)$"
    rex: "#it{H}_{T}(jet1, jet2)"
    unit: "GeV"
  HTratio_lep1lep2_lep1lep2jet1met:
    mpl: "$\\left. H_{\\mathrm{T}}(\\ell_1\\ell_2) \\right/ H_{\\mathrm{T}}(\\ell_1\\ell_2j_1E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: "#it{H}_{T}(lep1, lep2) / #it{H}_{T}(lep1, lep2, jet1, #{E}_{T}^{miss})"
    unit: ""
  HTratio_lep1lep2_lep1lep2jet1jet2met:
    mpl: "$\\left. H_{\\mathrm{T}}(\\ell_1\\ell_2) \\right/ H_{\\mathrm{T}}(\\ell_1\\ell_2j_1j_2E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: "#it{H}_{T}(lep1lep2) / #it{H}_{T}(lep1lep2jet1jet2#{E}_{T}^{miss})"
    unit: ""
  cent_lep1lep2:
    mpl: "Centrality($\\ell_1\\ell_2$)"
    rex: "Centrality(lep1, lep2)"
    unit: ""
  cent_lep1met:
    mpl: "Centrality($\\ell_1 E_{\\mathrm{T}}^{\\mathrm{miss}}$)"
    rex: "Centrality(lep1#it{E}_{T}^{miss})"
    unit: ""
  cent_lep1lep2jet1:
    mpl: "Centrality($\\ell_1\\ell_2j_1$)"
    rex: "Centrality(lep1lep2jet1)"
    unit: ""
  deltaR_jet1_jet2:
    mpl: "$\\Delta R (j_1, j_2)$"
    rex: "#Delta R(jet1, jet2)"
    unit: ""
  deltaR_lep1_jet1:
    mpl: "$\\Delta R (\\ell_1, j_1)$"
    rex: "#Delta R(lep1, jet1)"
    unit: ""
  deltaR_lep1_jet2:
    mpl: "$\\Delta R (\\ell_1, j_2)$"
    rex: "#Delta R(lep1, jet2)"
    unit: ""
  deltaR_lep1_lep2:
    mpl: "$\\Delta R (\\ell_1, \\ell_2)$"
    rex: "#Delta R(lep1, lep2)"
    unit: ""
  deltaR_lep1lep2_jet1jet2:
    mpl: "$\\Delta R (\\ell_1\\ell_2, j_1j_2)$"
    rex: ""
    unit: ""
  deltaR_lep1lep2_jet1jet2met:
    mpl: "$\\Delta R (\\ell_1\\ell_2, j_1j_2E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: ""
  deltaR_lep2_jet1:
    mpl: "$\\Delta R (\\ell_2, j_1)$"
    rex: ""
    unit: ""
  deltapT_jet2_met:
    mpl: "$\\Delta p_{\\mathrm{T}} (j_2, E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: "GeV"
  deltapT_lep1_jet1:
    mpl: "$\\Delta p_{\\mathrm{T}} (\\ell_1, j_1)$"
    rex: ""
    unit: "GeV"
  deltapT_lep1_lep2:
    mpl: "$\\Delta p_{\\mathrm{T}} (\\ell_1, \\ell_2)$"
    rex: ""
    unit: "GeV"
  deltapT_lep1lep2_jet1met:
    mpl: "$\\Delta p_{\\mathrm{T}} (\\ell_1\\ell_2, j_1E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: "GeV"
  deltapT_lep1lep2jet1_met:
    mpl: "$\\Delta p_{\\mathrm{T}} (\\ell_1\\ell_2j_1, E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: "GeV"
  eom_lep1lep2:
    mpl: "$\\frac{E}{m}(\\ell_1\\ell_2)$"
    rex: ""
    unit: ""
  mT_jet1met:
    mpl: "$m_{\\mathrm{T}}(j_1 E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: "GeV"
  mT_jet2met:
    mpl: "$m_{\\mathrm{T}}(j_2 E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: "GeV"
  mT_lep2met:
    mpl: "$m_{\\mathrm{T}}(\\ell_2 E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: "GeV"
  mass_lep1jet1:
    mpl: "$m(\\ell_1j_1)$"
    rex: ""
    unit: "GeV"
  mass_lep1jet1jet2:
    mpl: "$m(\\ell_1j_1j_2)$"
    rex: ""
    unit: "GeV"
  mass_lep1jet2:
    mpl: "$m(\\ell_1j_2)$"
    rex: ""
    unit: "GeV"
  mass_lep1lep2jet1jet2:
    mpl: "$m(\\ell_1\\ell_2j_1j_2)$"
    rex: ""
    unit: "GeV"
  mass_lep2jet1:
    mpl: "$m(\\ell_2j_1)$"
    rex: ""
    unit: "GeV"
  mass_lep2jet1jet2:
    mpl: "$m(\\ell_2j_1j_2)$"
    rex: ""
    unit: "GeV"
  mass_lep2jet1met:
    mpl: "$m(\\ell_2j_1E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: "GeV"
  mass_lep2jet2:
    mpl: "$m(\\ell_2j_2)$"
    rex: ""
    unit: "GeV"
  pTsys_jet1jet2:
    mpl: "$p_{\\mathrm{T}}^{\\mathrm{sys}} (j_1j_2)$"
    rex: ""
    unit: "GeV"
  pTsys_jet1met:
    mpl: "$p_{\\mathrm{T}}^{\\mathrm{sys}} (j_1E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: "GeV"
  pTsys_lep1lep2:
    mpl: "$p_{\\mathrm{T}}^{\\mathrm{sys}} (\\ell_1\\ell_2)$"
    rex: ""
    unit: "GeV"
  pTsys_lep1lep2jet1:
    mpl: "$p_{\\mathrm{T}}^{\\mathrm{sys}} (\\ell_1\\ell_2j_1)$"
    rex: ""
    unit: "GeV"
  pTsys_lep1lep2jet1jet2met:
    mpl: "$p_{\\mathrm{T}}^{\\mathrm{sys}} (\\ell_1\\ell_2j_1j_2E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: "GeV"
  pTsys_lep1lep2jet1met:
    mpl: "$p_{\\mathrm{T}}^{\\mathrm{sys}} (\\ell_1\\ell_2j_1E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: "GeV"
  pTsys_lep1lep2met:
    mpl: "$p_{\\mathrm{T}}^{\\mathrm{sys}} (\\ell_1\\ell_2E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: "GeV"
  pTHTratio_lep1lep2jet1met:
    mpl: "$\\frac{p_{\\mathrm{T}}}{H_{\\mathrm{T}}}(\\ell_1\\ell_2j_1E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: ""
  pTHTratio_lep1lep2jet1jet2met:
    mpl: "$\\frac{p_{\\mathrm{T}}}{H_{\\mathrm{T}}}(\\ell_1\\ell_2j_1j_2E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: ""
  phi_lep1:
    mpl: "$\\phi(\\ell_1)$"
    rex: ""
    unit: ""
  phi_lep2:
    mpl: "$\\phi(\\ell_2)$"
    rex: ""
    unit: ""
  phi_jet1:
    mpl: "$\\phi(j_1)$"
    rex: ""
    unit: ""
  phi_jet2:
    mpl: "$\\phi(j_2)$"
    rex: ""
    unit: ""
  E_lep1:
    mpl: "$E(\\ell_1)$"
    rex: ""
    unit: "GeV"
  E_lep2:
    mpl: "$E(\\ell_2)$"
    rex: ""
    unit: "GeV"
  E_jet1:
    mpl: "$E(j_1)$"
    rex: ""
    unit: "GeV"
  E_jet2:
    mpl: "$E(j_2)$"
    rex: ""
    unit: "GeV"
  phi_met:
    mpl: "$\\phi(E_{\\mathrm{T}}^{\\mathrm{miss}})$"
    rex: ""
    unit: ""
  sumet:
    mpl: "$\\sum E_{\\mathrm{T}}$"
    rex: ""
    unit: "GeV"
  nsoftjets:
    mpl: "$N$ soft jets"
    rex: "#it{N} soft jets"
    unit: ""
  nsoftbjets:
    mpl: "$N$ soft $b$-jets"
    rex: "#it{N} soft #it{b}-jets"
    unit: ""
  minimaxmbl:
    mpl: "minimax($m_{b\\ell}$)"
    rex: ""
    unit: "GeV"
  bdtres01:
    mpl: "BDT Response"
    rex: ""
    unit: ""


regions:
  r1j1b:
    - { var: pT_lep1, nbins: 40, xmin: 27.0, xmax: 227.0, log: false }
    - { var: pT_lep2, nbins: 40, xmin: 20.0, xmax: 160.0, log: false }
    - { var: pT_jet1, nbins: 40, xmin: 25.0, xmax: 225.0, log: false }
    - { var: met, nbins: 40, xmin: 0, xmax: 200, log: false }
    - { var: nsoftjets, nbins: 4, xmin: -0.5, xmax: 3.5, log: true }
    - { var: nsoftbjets, nbins: 3, xmin: -0.5, xmax: 2.5, log: true }
    - { var: HT_lep1lep2jet1met, nbins: 40, xmin: 100, xmax: 540, log: false }
    - { var: HTratio_lep1lep2_lep1lep2jet1met, nbins: 40, xmin: 0.15, xmax: 0.85, log: false }
    - { var: pTHTratio_lep1lep2jet1met, nbins: 40, xmin: 0.0, xmax: 0.5, log: false }
    - { var: bdtres01, nbins: 12, xmin: 0.18, xmax: 0.78, log: false }
  r2j1b:
    - { var: pT_lep1, nbins: 40, xmin: 27.0, xmax: 227.0, log: false }
    - { var: pT_lep2, nbins: 40, xmin: 20.0, xmax: 160.0, log: false }
    - { var: pT_jet1, nbins: 40, xmin: 25.0, xmax: 225.0, log: false }
    - { var: pT_jet2, nbins: 40, xmin: 25.0, xmax: 175.0, log: false }
    - { var: met, nbins: 40, xmin: 0, xmax: 200, log: false }
    # - { var: nsoftjets, nbins: 4, xmin: -0.5, xmax: 3.5, log: true }
    # - { var: nsoftbjets, nbins: 3, xmin: -0.5, xmax: 2.5, log: true }
    - { var: HT_lep1lep2jet1met, nbins: 40, xmin: 120, xmax: 580, log: false }
    - { var: HT_lep1lep2jet1jet2met, nbins: 40, xmin: 160, xmax: 780, log: false }
    - { var: HTratio_lep1lep2_lep1lep2jet1met, nbins: 40, xmin: 0.15, xmax: 0.8, log: false}
    - { var: pTHTratio_lep1lep2jet1met, nbins: 40, xmin: 0.0, xmax: 0.5, log: false }
    - { var: pTHTratio_lep1lep2jet1jet2met, nbins: 40, xmin: 0.0, xmax: 0.5, log: false }
  r2j2b:
    - { var: pT_lep1, nbins: 40, xmin: 27.0, xmax: 227.0, log: false }
    - { var: pT_lep2, nbins: 40, xmin: 20.0, xmax: 160.0, log: false }
    - { var: pT_jet1, nbins: 40, xmin: 25.0, xmax: 225.0, log: false }
    - { var: pT_jet2, nbins: 40, xmin: 25.0, xmax: 175.0, log: false }
    - { var: met, nbins: 40, xmin: 0, xmax: 200, log: false }
    - { var: HT_lep1lep2jet1met, nbins: 40, xmin: 120, xmax: 520, log: false }
    - { var: HT_lep1lep2jet1jet2met, nbins: 40, xmin: 200, xmax: 800, log: false }
    - { var: HTratio_lep1lep2_lep1lep2jet1met, nbins: 40, xmin: 0.2, xmax: 0.8, log: false }
